#
# Copyright (C) 2018,  Netronome Systems, Inc.  All rights reserved.
#
"""
eBPF performance test group for the NFP Linux drivers.
"""
import os, pprint
import time
import netro.testinfra
from netro.testinfra.nti_exceptions import NtiGeneralError
from netro.testinfra.test import *
from ..common_test import *
from ..drv_grp import NFPKmodGrp
from ..ebpf_test import *
from ..ebpf.tests import *
from perf import *
from synthetic_tests import *

###########################################################################
# Group
###########################################################################

class NFPKmodBPFPerf(NFPKmodBPF):
    """eBPF XDP performance tests for the NFP Linux drivers"""

    summary = "BPF tests to detect performance regressions."

    def __init__(self, name, cfg=None, quick=False, dut_object=None,
                 dut=None, nfp=None, nfpkmods=None, mefw=None):

        NFPKmodGrp.__init__(self, name=name, cfg=cfg, quick=quick,
                            dut_object=dut_object)

    def xdp_mode(self):
        return "offload"

    def populate_tests(self):
        dut = (self.dut, self.addr_x, self.eth_x, self.addr_v6_x)
        src = (self.host_a, self.addr_a, self.eth_a, self.addr_v6_a)

        ebpf_perf_xdp = (
            ('XDPpass',  XDPperf, 'XDP perf test', 'pass.o',
             'dev_rx_pkts', 'bpf_pass_pkts'),
            ('XDPdrop',  XDPperf, 'XDP perf test', 'drop.o',
             'dev_rx_pkts', 'bpf_app1_pkts'),
            ('XDPtx',  XDPperf, 'XDP perf test', 'tx.o',
             'dev_tx_pkts', 'bpf_app2_pkts'),
            ('random_gen_128',  RANDperf, 'XDP perf test', 'random_gen_128.o',
             'dev_tx_pkts', 'bpf_app2_pkts'),
        )
        for t in ebpf_perf_xdp:
            self._tests[t[0]] = t[1](src, dut, group=self, name=t[0],
                                     summary=t[2], objfile=t[3],
                                     drv_pkt_cntr=t[4], off_pkt_cntr=t[5])

        ebpf_perf_pre_subset = (
            ('pre_FF_0_opt_1_lookup', SyntheticProg, 'perf pre',
             '0xFF_mask_0_optionals_1_lookups.o', 255, 0),
            ('pre_FFF_0_opt_2_lookup', SyntheticProg, 'perf pre',
             '0xFFF_mask_0_optionals_2_lookups.o', 4095, 0),
            ('pre_FFF_0_opt_2_lookup_atom', SyntheticProg, 'perf pre',
             '0xFFF_mask_0_optionals_2_lookups_atomic.o', 4095, 0),
            ('pre_FFF_3_opt_3_lookup', SyntheticProg, 'perf pre',
             '0xFFF_mask_3_optionals_3_lookups.o', 4095, 1),
            ('pre_FFF_5_opt_2_lookup', SyntheticProg, 'perf pre',
             '0xFFF_mask_5_optionals_2_lookups.o', 4095, 1),
            ('pre_FFFF_0_opt_1_lookup', SyntheticProg, 'perf pre',
             '0xFFFF_mask_0_optionals_1_lookups.o', 65535, 0),
            ('pre_FFFF_3_opt_3_lookup', SyntheticProg, 'perf pre',
             '0xFFFF_mask_3_optionals_3_lookups.o', 65535, 1),
            ('pre_FFFF_4_opt_4_lookup', SyntheticProg, 'perf pre',
             '0xFFFF_mask_4_optionals_4_lookups.o', 65535, 1),
            ('pre_FFFF_4_opt_4_lookup_atom', SyntheticProg, 'perf pre',
             '0xFFFF_mask_4_optionals_4_lookups_atomic.o', 65535, 1),
            ('pre_7FFFF_5_opt_5_lookup', SyntheticProg, 'perf pre',
             '0x7FFFF_mask_5_optionals_5_lookups.o', 524287, 1)
        )
        for t in ebpf_perf_pre_subset:
            self._tests[t[0]] = t[1](src, dut, group=self, name=t[0],
                                     summary=t[2], objfile=t[3],
                                     map_records=t[4], packet_extend=t[5])

        ebpf_perf = (
            ('0xFF_0_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_1_lookups.o', 255, 0),
            ('0xFF_0_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_1_lookups_atomic.o', 255, 0),
            ('0xFF_0_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_2_lookups.o', 255, 0),
            ('0xFF_0_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_2_lookups_atomic.o', 255, 0),
            ('0xFF_0_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_3_lookups.o', 255, 0),
            ('0xFF_0_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_3_lookups_atomic.o', 255, 0),
            ('0xFF_0_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_4_lookups.o', 255, 0),
            ('0xFF_0_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_4_lookups_atomic.o', 255, 0),
            ('0xFF_0_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_5_lookups.o', 255, 0),
            ('0xFF_0_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_0_optionals_5_lookups_atomic.o', 255, 0),
            ('0xFF_1_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_1_lookups.o', 255, 1),
            ('0xFF_1_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_1_lookups_atomic.o', 255, 1),
            ('0xFF_1_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_2_lookups.o', 255, 1),
            ('0xFF_1_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_2_lookups_atomic.o', 255, 1),
            ('0xFF_1_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_3_lookups.o', 255, 1),
            ('0xFF_1_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_3_lookups_atomic.o', 255, 1),
            ('0xFF_1_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_4_lookups.o', 255, 1),
            ('0xFF_1_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_4_lookups_atomic.o', 255, 1),
            ('0xFF_1_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_5_lookups.o', 255, 1),
            ('0xFF_1_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_1_optionals_5_lookups_atomic.o', 255, 1),
            ('0xFF_2_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_1_lookups.o', 255, 1),
            ('0xFF_2_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_1_lookups_atomic.o', 255, 1),
            ('0xFF_2_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_2_lookups.o', 255, 1),
            ('0xFF_2_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_2_lookups_atomic.o', 255, 1),
            ('0xFF_2_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_3_lookups.o', 255, 1),
            ('0xFF_2_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_3_lookups_atomic.o', 255, 1),
            ('0xFF_2_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_4_lookups.o', 255, 1),
            ('0xFF_2_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_4_lookups_atomic.o', 255, 1),
            ('0xFF_2_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_5_lookups.o', 255, 1),
            ('0xFF_2_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_2_optionals_5_lookups_atomic.o', 255, 1),
            ('0xFF_3_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_1_lookups.o', 255, 1),
            ('0xFF_3_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_1_lookups_atomic.o', 255, 1),
            ('0xFF_3_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_2_lookups.o', 255, 1),
            ('0xFF_3_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_2_lookups_atomic.o', 255, 1),
            ('0xFF_3_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_3_lookups.o', 255, 1),
            ('0xFF_3_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_3_lookups_atomic.o', 255, 1),
            ('0xFF_3_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_4_lookups.o', 255, 1),
            ('0xFF_3_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_4_lookups_atomic.o', 255, 1),
            ('0xFF_3_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_5_lookups.o', 255, 1),
            ('0xFF_3_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_3_optionals_5_lookups_atomic.o', 255, 1),
            ('0xFF_4_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_1_lookups.o', 255, 1),
            ('0xFF_4_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_1_lookups_atomic.o', 255, 1),
            ('0xFF_4_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_2_lookups.o', 255, 1),
            ('0xFF_4_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_2_lookups_atomic.o', 255, 1),
            ('0xFF_4_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_3_lookups.o', 255, 1),
            ('0xFF_4_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_3_lookups_atomic.o', 255, 1),
            ('0xFF_4_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_4_lookups.o', 255, 1),
            ('0xFF_4_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_4_lookups_atomic.o', 255, 1),
            ('0xFF_4_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_5_lookups.o', 255, 1),
            ('0xFF_4_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_4_optionals_5_lookups_atomic.o', 255, 1),
            ('0xFF_5_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_1_lookups.o', 255, 1),
            ('0xFF_5_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_1_lookups_atomic.o', 255, 1),
            ('0xFF_5_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_2_lookups.o', 255, 1),
            ('0xFF_5_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_2_lookups_atomic.o', 255, 1),
            ('0xFF_5_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_3_lookups.o', 255, 1),
            ('0xFF_5_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_3_lookups_atomic.o', 255, 1),
            ('0xFF_5_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_4_lookups.o', 255, 1),
            ('0xFF_5_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_4_lookups_atomic.o', 255, 1),
            ('0xFF_5_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_5_lookups.o', 255, 1),
            ('0xFF_5_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFF_mask_5_optionals_5_lookups_atomic.o', 255, 1),
            ('0xFFF_0_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_1_lookups.o', 4095, 0),
            ('0xFFF_0_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_1_lookups_atomic.o', 4095, 0),
            ('0xFFF_0_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_2_lookups.o', 4095, 0),
            ('0xFFF_0_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_2_lookups_atomic.o', 4095, 0),
            ('0xFFF_0_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_3_lookups.o', 4095, 0),
            ('0xFFF_0_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_3_lookups_atomic.o', 4095, 0),
            ('0xFFF_0_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_4_lookups.o', 4095, 0),
            ('0xFFF_0_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_4_lookups_atomic.o', 4095, 0),
            ('0xFFF_0_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_5_lookups.o', 4095, 0),
            ('0xFFF_0_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_0_optionals_5_lookups_atomic.o', 4095, 0),
            ('0xFFF_1_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_1_lookups.o', 4095, 1),
            ('0xFFF_1_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_1_lookups_atomic.o', 4095, 1),
            ('0xFFF_1_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_2_lookups.o', 4095, 1),
            ('0xFFF_1_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_2_lookups_atomic.o', 4095, 1),
            ('0xFFF_1_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_3_lookups.o', 4095, 1),
            ('0xFFF_1_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_3_lookups_atomic.o', 4095, 1),
            ('0xFFF_1_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_4_lookups.o', 4095, 1),
            ('0xFFF_1_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_4_lookups_atomic.o', 4095, 1),
            ('0xFFF_1_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_5_lookups.o', 4095, 1),
            ('0xFFF_1_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_1_optionals_5_lookups_atomic.o', 4095, 1),
            ('0xFFF_2_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_1_lookups.o', 4095, 1),
            ('0xFFF_2_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_1_lookups_atomic.o', 4095, 1),
            ('0xFFF_2_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_2_lookups.o', 4095, 1),
            ('0xFFF_2_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_2_lookups_atomic.o', 4095, 1),
            ('0xFFF_2_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_3_lookups.o', 4095, 1),
            ('0xFFF_2_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_3_lookups_atomic.o', 4095, 1),
            ('0xFFF_2_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_4_lookups.o', 4095, 1),
            ('0xFFF_2_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_4_lookups_atomic.o', 4095, 1),
            ('0xFFF_2_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_5_lookups.o', 4095, 1),
            ('0xFFF_2_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_2_optionals_5_lookups_atomic.o', 4095, 1),
            ('0xFFF_3_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_1_lookups.o', 4095, 1),
            ('0xFFF_3_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_1_lookups_atomic.o', 4095, 1),
            ('0xFFF_3_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_2_lookups.o', 4095, 1),
            ('0xFFF_3_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_2_lookups_atomic.o', 4095, 1),
            ('0xFFF_3_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_3_lookups.o', 4095, 1),
            ('0xFFF_3_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_3_lookups_atomic.o', 4095, 1),
            ('0xFFF_3_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_4_lookups.o', 4095, 1),
            ('0xFFF_3_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_4_lookups_atomic.o', 4095, 1),
            ('0xFFF_3_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_5_lookups.o', 4095, 1),
            ('0xFFF_3_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_3_optionals_5_lookups_atomic.o', 4095, 1),
            ('0xFFF_4_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_1_lookups.o', 4095, 1),
            ('0xFFF_4_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_1_lookups_atomic.o', 4095, 1),
            ('0xFFF_4_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_2_lookups.o', 4095, 1),
            ('0xFFF_4_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_2_lookups_atomic.o', 4095, 1),
            ('0xFFF_4_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_3_lookups.o', 4095, 1),
            ('0xFFF_4_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_3_lookups_atomic.o', 4095, 1),
            ('0xFFF_4_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_4_lookups.o', 4095, 1),
            ('0xFFF_4_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_4_lookups_atomic.o', 4095, 1),
            ('0xFFF_4_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_5_lookups.o', 4095, 1),
            ('0xFFF_4_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_4_optionals_5_lookups_atomic.o', 4095, 1),
            ('0xFFF_5_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_1_lookups.o', 4095, 1),
            ('0xFFF_5_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_1_lookups_atomic.o', 4095, 1),
            ('0xFFF_5_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_2_lookups.o', 4095, 1),
            ('0xFFF_5_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_2_lookups_atomic.o', 4095, 1),
            ('0xFFF_5_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_3_lookups.o', 4095, 1),
            ('0xFFF_5_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_3_lookups_atomic.o', 4095, 1),
            ('0xFFF_5_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_4_lookups.o', 4095, 1),
            ('0xFFF_5_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_4_lookups_atomic.o', 4095, 1),
            ('0xFFF_5_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_5_lookups.o', 4095, 1),
            ('0xFFF_5_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFF_mask_5_optionals_5_lookups_atomic.o', 4095, 1),
            ('0xFFFF_0_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_1_lookups.o', 65535, 0),
            ('0xFFFF_0_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_1_lookups_atomic.o', 65535, 0),
            ('0xFFFF_0_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_2_lookups.o', 65535, 0),
            ('0xFFFF_0_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_2_lookups_atomic.o', 65535, 0),
            ('0xFFFF_0_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_3_lookups.o', 65535, 0),
            ('0xFFFF_0_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_3_lookups_atomic.o', 65535, 0),
            ('0xFFFF_0_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_4_lookups.o', 65535, 0),
            ('0xFFFF_0_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_4_lookups_atomic.o', 65535, 0),
            ('0xFFFF_0_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_5_lookups.o', 65535, 0),
            ('0xFFFF_0_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_0_optionals_5_lookups_atomic.o', 65535, 0),
            ('0xFFFF_1_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_1_lookups.o', 65535, 1),
            ('0xFFFF_1_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_1_lookups_atomic.o', 65535, 1),
            ('0xFFFF_1_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_2_lookups.o', 65535, 1),
            ('0xFFFF_1_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_2_lookups_atomic.o', 65535, 1),
            ('0xFFFF_1_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_3_lookups.o', 65535, 1),
            ('0xFFFF_1_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_3_lookups_atomic.o', 65535, 1),
            ('0xFFFF_1_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_4_lookups.o', 65535, 1),
            ('0xFFFF_1_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_4_lookups_atomic.o', 65535, 1),
            ('0xFFFF_1_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_5_lookups.o', 65535, 1),
            ('0xFFFF_1_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_1_optionals_5_lookups_atomic.o', 65535, 1),
            ('0xFFFF_2_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_1_lookups.o', 65535, 1),
            ('0xFFFF_2_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_1_lookups_atomic.o', 65535, 1),
            ('0xFFFF_2_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_2_lookups.o', 65535, 1),
            ('0xFFFF_2_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_2_lookups_atomic.o', 65535, 1),
            ('0xFFFF_2_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_3_lookups.o', 65535, 1),
            ('0xFFFF_2_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_3_lookups_atomic.o', 65535, 1),
            ('0xFFFF_2_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_4_lookups.o', 65535, 1),
            ('0xFFFF_2_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_4_lookups_atomic.o', 65535, 1),
            ('0xFFFF_2_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_5_lookups.o', 65535, 1),
            ('0xFFFF_2_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_2_optionals_5_lookups_atomic.o', 65535, 1),
            ('0xFFFF_3_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_1_lookups.o', 65535, 1),
            ('0xFFFF_3_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_1_lookups_atomic.o', 65535, 1),
            ('0xFFFF_3_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_2_lookups.o', 65535, 1),
            ('0xFFFF_3_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_2_lookups_atomic.o', 65535, 1),
            ('0xFFFF_3_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_3_lookups.o', 65535, 1),
            ('0xFFFF_3_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_3_lookups_atomic.o', 65535, 1),
            ('0xFFFF_3_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_4_lookups.o', 65535, 1),
            ('0xFFFF_3_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_4_lookups_atomic.o', 65535, 1),
            ('0xFFFF_3_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_5_lookups.o', 65535, 1),
            ('0xFFFF_3_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_3_optionals_5_lookups_atomic.o', 65535, 1),
            ('0xFFFF_4_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_1_lookups.o', 65535, 1),
            ('0xFFFF_4_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_1_lookups_atomic.o', 65535, 1),
            ('0xFFFF_4_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_2_lookups.o', 65535, 1),
            ('0xFFFF_4_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_2_lookups_atomic.o', 65535, 1),
            ('0xFFFF_4_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_3_lookups.o', 65535, 1),
            ('0xFFFF_4_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_3_lookups_atomic.o', 65535, 1),
            ('0xFFFF_4_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_4_lookups.o', 65535, 1),
            ('0xFFFF_4_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_4_lookups_atomic.o', 65535, 1),
            ('0xFFFF_4_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_5_lookups.o', 65535, 1),
            ('0xFFFF_4_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_4_optionals_5_lookups_atomic.o', 65535, 1),
            ('0xFFFF_5_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_1_lookups.o', 65535, 1),
            ('0xFFFF_5_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_1_lookups_atomic.o', 65535, 1),
            ('0xFFFF_5_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_2_lookups.o', 65535, 1),
            ('0xFFFF_5_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_2_lookups_atomic.o', 65535, 1),
            ('0xFFFF_5_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_3_lookups.o', 65535, 1),
            ('0xFFFF_5_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_3_lookups_atomic.o', 65535, 1),
            ('0xFFFF_5_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_4_lookups.o', 65535, 1),
            ('0xFFFF_5_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_4_lookups_atomic.o', 65535, 1),
            ('0xFFFF_5_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_5_lookups.o', 65535, 1),
            ('0xFFFF_5_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0xFFFF_mask_5_optionals_5_lookups_atomic.o', 65535, 1),
            ('0x7FFFF_0_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_1_lookups.o', 524287, 0),
            ('0x7FFFF_0_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_1_lookups_atomic.o', 524287, 0),
            ('0x7FFFF_0_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_2_lookups.o', 524287, 0),
            ('0x7FFFF_0_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_2_lookups_atomic.o', 524287, 0),
            ('0x7FFFF_0_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_3_lookups.o', 524287, 0),
            ('0x7FFFF_0_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_3_lookups_atomic.o', 524287, 0),
            ('0x7FFFF_0_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_4_lookups.o', 524287, 0),
            ('0x7FFFF_0_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_4_lookups_atomic.o', 524287, 0),
            ('0x7FFFF_0_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_5_lookups.o', 524287, 0),
            ('0x7FFFF_0_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_0_optionals_5_lookups_atomic.o', 524287, 0),
            ('0x7FFFF_1_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_1_lookups.o', 524287, 1),
            ('0x7FFFF_1_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_1_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_1_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_2_lookups.o', 524287, 1),
            ('0x7FFFF_1_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_2_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_1_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_3_lookups.o', 524287, 1),
            ('0x7FFFF_1_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_3_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_1_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_4_lookups.o', 524287, 1),
            ('0x7FFFF_1_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_4_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_1_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_5_lookups.o', 524287, 1),
            ('0x7FFFF_1_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_1_optionals_5_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_2_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_1_lookups.o', 524287, 1),
            ('0x7FFFF_2_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_1_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_2_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_2_lookups.o', 524287, 1),
            ('0x7FFFF_2_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_2_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_2_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_3_lookups.o', 524287, 1),
            ('0x7FFFF_2_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_3_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_2_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_4_lookups.o', 524287, 1),
            ('0x7FFFF_2_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_4_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_2_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_5_lookups.o', 524287, 1),
            ('0x7FFFF_2_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_2_optionals_5_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_3_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_1_lookups.o', 524287, 1),
            ('0x7FFFF_3_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_1_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_3_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_2_lookups.o', 524287, 1),
            ('0x7FFFF_3_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_2_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_3_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_3_lookups.o', 524287, 1),
            ('0x7FFFF_3_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_3_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_3_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_4_lookups.o', 524287, 1),
            ('0x7FFFF_3_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_4_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_3_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_5_lookups.o', 524287, 1),
            ('0x7FFFF_3_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_3_optionals_5_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_4_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_1_lookups.o', 524287, 1),
            ('0x7FFFF_4_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_1_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_4_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_2_lookups.o', 524287, 1),
            ('0x7FFFF_4_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_2_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_4_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_3_lookups.o', 524287, 1),
            ('0x7FFFF_4_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_3_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_4_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_4_lookups.o', 524287, 1),
            ('0x7FFFF_4_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_4_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_4_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_5_lookups.o', 524287, 1),
            ('0x7FFFF_4_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_4_optionals_5_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_5_opt_1_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_1_lookups.o', 524287, 1),
            ('0x7FFFF_5_opt_1_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_1_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_5_opt_2_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_2_lookups.o', 524287, 1),
            ('0x7FFFF_5_opt_2_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_2_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_5_opt_3_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_3_lookups.o', 524287, 1),
            ('0x7FFFF_5_opt_3_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_3_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_5_opt_4_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_4_lookups.o', 524287, 1),
            ('0x7FFFF_5_opt_4_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_4_lookups_atomic.o', 524287, 1),
            ('0x7FFFF_5_opt_5_lookup', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_5_lookups.o', 524287, 1),
            ('0x7FFFF_5_opt_5_lookup_atom', SyntheticProg, 'XDP perf test',
             '0x7FFFF_mask_5_optionals_5_lookups_atomic.o', 524287, 1),
            )

        for t in ebpf_perf:
            self._tests[t[0]] = t[1](src, dut, group=self, name=t[0],
                                     summary=t[2], objfile=t[3],
                                     map_records=t[4], packet_extend=t[5])

    def _init(self):
        NFPKmodAppGrp._init(self)
        self.dut.copy_c_samples()
        self.dut.copy_bpf_samples()
        self.dut.copy_bpf_perf_samples()
        self.dut.copy_xdp_samples()
        self.parse_bpf_caps()
        time.sleep(1) # allow for trafgen to start
        return

class NFPKmodBPFPerfdrv(NFPKmodBPFPerf):
    def _init(self):
        NFPKmodBPFPerf._init(self)
        for p in range(len(self.eth_x)):
            self.dut.cmd('ethtool -L %s rx 0 tx 0 combined 1' % self.eth_x[p])

    def xdp_mode(self):
        return "drv"
